services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: bomatic
      POSTGRES_USER: bomatic
      POSTGRES_PASSWORD: bomatic
    ports:
      - "9876:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
