"""add tenant_id and user_id to opportunity

Revision ID: db9306598689
Revises: 2bcbe2a82919
Create Date: 2026-05-16 13:01:23.283541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9306598689'
down_revision: Union[str, None] = '2bcbe2a82919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('tenant_id', sa.String(length=100), nullable=False))
    op.add_column('opportunities', sa.Column('user_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'user_id')
    op.drop_column('opportunities', 'tenant_id')
    # ### end Alembic commands ###
