from typing import Any, Literal, Mapping

from fastapi import HTTPException
from pydantic import BaseModel, ConfigDict, Field, ValidationError


class E1Output(BaseModel):
    model_config = ConfigDict(extra="ignore")

    vendor_list: list[str]
    requirements_baseline: list[dict]
    risk_flags: list[dict]
    sector: str
    frameworks_selected: list[str]


class E2PricingLine(BaseModel):
    model_config = ConfigDict(extra="ignore")

    sku: str = ""
    product_name: str = ""
    description: str = ""
    quantity: float | None = None
    unit_price: float = Field(default=0.0, ge=0.0)


class E2PricingArtifact(BaseModel):
    """Versioned contract persisted by E2 and consumed by downstream engines."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e2_pricing"] = "e2_pricing"
    schema_version: Literal[1] = 1
    matched_items: list[E2PricingLine] = Field(default_factory=list)
    unmatched_items: list[E2PricingLine] = Field(default_factory=list)
    subtotal: float = Field(default=0.0, ge=0.0)
    discount_amount: float = Field(default=0.0, ge=0.0)
    total: float = Field(default=0.0, ge=0.0)
    currency: str = Field(default="USD", min_length=3, max_length=3)
    matched_count: int = Field(default=0, ge=0)
    unmatched_count: int = Field(default=0, ge=0)
    low_confidence_count: int = Field(default=0, ge=0)
    vendor_list: list[str] = Field(default_factory=list)
    output_file: str = ""
    eox_warnings: list[dict[str, Any]] = Field(default_factory=list)
    cost_stack: dict[str, Any] = Field(default_factory=dict)
    cost_config: dict[str, Any] = Field(default_factory=dict)

    @classmethod
    def from_pricing_summary(cls, summary) -> "E2PricingArtifact":
        return cls(
            matched_items=[
                E2PricingLine(
                    sku=match.sku,
                    product_name=match.product_name,
                    description=match.rfp_item.description,
                    quantity=match.rfp_item.quantity,
                    unit_price=match.unit_price,
                )
                for match in summary.matched_items
            ],
            unmatched_items=[
                E2PricingLine(
                    description=match.rfp_item.description,
                    quantity=match.rfp_item.quantity,
                )
                for match in summary.unmatched_items
            ],
            subtotal=summary.subtotal,
            discount_amount=summary.discount_amount,
            total=summary.total,
            currency=summary.currency,
        )


class E3ProposalArtifact(BaseModel):
    """Versioned proposal summary persisted by E3 and consumed by the UI."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e3_proposal"] = "e3_proposal"
    schema_version: Literal[1] = 1
    output_file: str = ""
    pdf_file: str | None = None
    project_name: str = ""
    section_count: int = Field(default=0, ge=0)
    ai_generated_count: int = Field(default=0, ge=0)
    gbb_tier: str = "better"
    gbb_multiplier: float = Field(default=1.0, ge=0.0)
    total_price: float = Field(default=0.0, ge=0.0)
    e4_requirement_count: int = Field(default=0, ge=0)
    e4_gap_count: int = Field(default=0, ge=0)
    e5_component_count: int = Field(default=0, ge=0)


class E4QuestionnaireQuestion(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: str
    category: str = "General"
    question: str
    rationale: str = ""
    priority: str = "must_have"
    expected_answer_type: str = "text"


class E4QuestionnaireArtifact(BaseModel):
    """Versioned questionnaire generated by E4 and persisted for reviews."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e4_questionnaire"] = "e4_questionnaire"
    schema_version: Literal[1] = 1
    output_file: str = ""
    project_name: str = ""
    total_questions: int = Field(default=0, ge=0)
    categories: list[str] = Field(default_factory=list)
    generated_from: str = "blank"
    must_have_count: int = Field(default=0, ge=0)
    nice_to_have_count: int = Field(default=0, ge=0)
    questions: list[E4QuestionnaireQuestion] = Field(default_factory=list)


class E4BaselineRequirement(BaseModel):
    model_config = ConfigDict(extra="ignore")

    question_id: str
    category: str = "General"
    question: str
    answer: str = ""
    priority: str = "must_have"
    expected_answer_type: str = "text"
    status: Literal["answered", "missing", "insufficient"]
    gap_reason: str | None = None


class E4BaselineArtifact(BaseModel):
    """Validated RFI response baseline persisted by E4 for downstream engines."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e4_requirements_baseline"] = "e4_requirements_baseline"
    schema_version: Literal[1] = 1
    source_filename: str = ""
    requirements: list[E4BaselineRequirement] = Field(default_factory=list)
    answered_count: int = Field(default=0, ge=0)
    gap_count: int = Field(default=0, ge=0)


class E5Component(BaseModel):
    model_config = ConfigDict(extra="ignore")

    description: str
    quantity: float = Field(default=1.0, gt=0.0)
    unit: str = "units"
    category: str = "hardware"
    source_sections: list[str] = Field(default_factory=list)


class E5DesignArtifact(BaseModel):
    """Versioned design summary persisted by E5 for the pipeline UI."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e5_design"] = "e5_design"
    schema_version: Literal[1] = 1
    output_file: str = ""
    project_name: str = ""
    hld_section_count: int = Field(default=0, ge=0)
    lld_section_count: int = Field(default=0, ge=0)
    generated_from: str = "blank"
    total_sections: int = Field(default=0, ge=0)


class E5ComponentArtifact(BaseModel):
    """Versioned component handoff generated by E5 and consumed by E2."""

    model_config = ConfigDict(extra="allow")

    artifact_type: Literal["e5_components"] = "e5_components"
    schema_version: Literal[1] = 1
    components: list[E5Component] = Field(default_factory=list)


class PipelineStateOutputs(BaseModel):
    """Validated wrapper around the JSONB step_outputs contract."""

    model_config = ConfigDict(extra="allow", populate_by_name=True)

    e1: E1Output | None = None
    e2: E2PricingArtifact | None = None
    e3: E3ProposalArtifact | None = None
    e4: E4QuestionnaireArtifact | None = None
    e4_baseline: E4BaselineArtifact | None = None
    e5: E5DesignArtifact | None = None
    e5_components: E5ComponentArtifact | None = None
    review_cp1: dict[str, Any] | None = None
    review_cp2: dict[str, Any] | None = None
    review_e2: dict[str, Any] | None = None
    review_e3: dict[str, Any] | None = None
    review_e4: dict[str, Any] | None = None
    review_e5: dict[str, Any] | None = None
    revision_counts: dict[str, int] = Field(default_factory=dict)
    revision_notes: dict[str, str] = Field(default_factory=dict)
    step_2: list[dict[str, Any]] = Field(default_factory=list, alias="2")
    step_3: list[dict[str, Any]] = Field(default_factory=list, alias="3")
    step_4: list[dict[str, Any]] = Field(default_factory=list, alias="4")
    step_8: dict[str, Any] = Field(default_factory=dict, alias="8")
    step_9: list[str] = Field(default_factory=list, alias="9")
    step_10: list[dict[str, Any]] = Field(default_factory=list, alias="10")
    xlsx_path: str = ""
    requirements_docx_path: str = ""
    gaps: dict[str, Any] = Field(default_factory=dict)
    stats: dict[str, Any] = Field(default_factory=dict)


def deserialize_pipeline_state_outputs(
    raw: Mapping[str, Any] | PipelineStateOutputs | None,
) -> PipelineStateOutputs:
    if isinstance(raw, PipelineStateOutputs):
        return raw
    try:
        return PipelineStateOutputs.model_validate(raw or {})
    except ValidationError as exc:
        raise HTTPException(status_code=422, detail=exc.errors()) from exc


def serialize_pipeline_state_outputs(
    outputs: Mapping[str, Any] | PipelineStateOutputs | None,
) -> dict[str, Any]:
    try:
        model = (
            outputs
            if isinstance(outputs, PipelineStateOutputs)
            else PipelineStateOutputs.model_validate(outputs or {})
        )
        return model.model_dump(mode="json", by_alias=True, exclude_none=True)
    except ValidationError as exc:
        raise HTTPException(status_code=422, detail=exc.errors()) from exc
